### PR TITLE
Feature/disable kll profiling by default

### PR DESCRIPTION
**Pull request by rambrus**
*Issue #, if available:*

*Description of changes:*
Disable KLL metrics calculation in profiling by default. (since this feature has high risk of performance degradation)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by rambrus** [comment]
@sscdotopen Could you please take a quick look at this draft PR? Disabled the KLL metrics calculation in profiling by default, updated the related test cases, however facing an issue:

My changes are breaking one of the *scalastyle rules*:
```
error file=/home/travis/build/awslabs/deequ/src/main/scala/com/amazon/deequ/profiles/ColumnProfiler.scala message=argcount.message line=91 column=21
```

I had to add a `Boolean` flag to `ColumnProfiler.profile` method so that we can turn on / off the KLL metrics calculation, see [here](https://github.com/awslabs/deequ/blob/931d3efa0e34e69ec77e6fa37cca17c82ffbc370/src/main/scala/com/amazon/deequ/profiles/ColumnProfiler.scala#L101)

The number of parameters increased to 11 and *scalastyle rules* do not allow to have more than 10 parameters (which makes perfect sense).

I think the whole class should be refactored to fix this issue properly. Any advice on this?

Thanks,
Robert

**Comment by sscdotopen** [comment]
Thank you for this great work. Feel free to just edit the scalastyle file to allow for a maximum of 11 parameters.

Best,
Sebastian

**Comment by sscdotopen** [comment]
Seems this did not help, the build is still failing.

**Comment by rambrus** [comment]
@sscdotopen yeah, I tried to avoid adjusting the scalastyle rule on the entire project, just suppressed the rule on the particular method, used wrong rule id at first, corrected now.

**Comment by sscdotopen** [comment]
Thank you!!

**Pull request merged**
