### PR TITLE
Update build setup

### PR DESCRIPTION
**Pull request by twollnik**
### Issue #, if available:
https://github.com/awslabs/deequ/issues/283

### Description of changes:

This PR updates the build setup as discussed in https://github.com/awslabs/deequ/issues/283. @sscdotopen Please let me know if the proposed changes are in line with your thoughts on this matter and which further actions need to be taken.

Changes:
- Explicitly set the spark and scala versions for all maven profiles (spark 2.x uses scala 2.11, spark 3 uses scala 2.12)
- Include spark and scala versions in jar name (e.g. `deequ_scala-2.11_spark-2.4`)
- Use Makefile variable `MVN_PROFILE` to select the profile for the current build

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by twollnik** [comment]
Travis fails with the message `The job exceeded the maximum log length, and has been terminated`. Can someone with the necessary permissions please restart the job?

**Comment by sscdotopen** [comment]
Hi Tom,
I think the people with the necessary permissions are @iamsteps and @tdhd

**Comment by sscdotopen** [comment]
The PR looks good, can you check whether the artifacts work correctly on a real cluster, for example on EMR?

**Comment by twollnik** [comment]
Thanks for taking a look. I will test the artifacts on a real cluster later today.

**Comment by twollnik** [comment]
Hi @sscdotopen,

I tested the jars created by the updated build profiles and they all seem to work properly. I spun up EMR clusters for the different spark versions and ran the first example mentioned in [this blog post](https://aws.amazon.com/blogs/big-data/test-data-quality-at-scale-with-deequ/) on the clusters using the corresponding deequ jars. No errors occurred and the resulting dataframe contained the expected output.

I have two questions:
1. Are we ready to merge or is there anything left to do? 
2. After this PR is merged, do we still need to call `mvn clean deploy ...`?

**Comment by sscdotopen** [comment]
Hi Tom, the build is still failing on travis, I guess thats the first things that we should fix. Afterwards, we should be good to merge. We then need to cut a release with the new jars, @iamsteps knows how to do that.

**Comment by twollnik** [comment]
Okay, thanks.

**Comment by twollnik** [comment]
@iamsteps 
The travis build is green now. I made the following changes to the Makefile:

- Added the `-q` flag to the make target `build` to reduce the number of log messages and make the travis checks pass.
- Added make variable for mvn build profile (`MVN_PROFILE`) and used the new variable in the make targets. This should make it easier for users to switch between the different profiles. It also makes it possible to set the `MVN_PROFILE` on the command line (`make MVN_PROFILE=xxx build`).
- Added comments to all sections of the Makefile for improved accessibility. 
- Added the comment `Deprecated` to the target `travis-deploy` as we are still doing manual deployments. We could get rid of this target all together.

We already discussed issues with the current CI/CD setup. It is less than ideal because we are building the project only for the mvn profile `spark-3.0-scala-2.12` and we are not running any tests on real EMR clusters. We should open a ticket and spend some time on improving the CI/CD setup next year.

**Comment by twollnik** [comment]
Got verbal approval from @iamsteps. merging now.

**Pull request merged**
