### PR TITLE
Feature/deequ 149 easy part

### PR DESCRIPTION
**Pull request by rambrus**
*Issue #, if available:*
https://github.com/awslabs/deequ/issues/149

*Description of changes:*
This PR is covering the easy part of https://github.com/awslabs/deequ/issues/149, making the following Checks filterable:
- hasMean
- hasPattern
- containsCreditCardNumber
- containsEmail
- containsURL
- containsSocialSecurityNumber

Replaced `Check` return type with `CheckWithLastConstraintFilterable` and updated the test cases accordingly.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by rambrus** [comment]
@esil-esil this PR is making most of the Checks filterable that you are interested in.

**Comment by esil-esil** [comment]
Sounds really great - thank you very much, @rambrus !

As of March 6th 2020, latest pre-release is still 1.0.3-rc1 released on December 19th 2019, with 12 new commits since release (including your commits).

Assuming that I will have to wait for the next (pre-)release of the Deequ Lib for your changes to be included?

**Comment by rambrus** [comment]
I'm not sure about the release schedule, but I would be also interested.

@sscdotopen Could you please clarify the release plans?

**Comment by sscdotopen** [comment]
I would love to cut another release soon. I am a bit worried though about some performance regressions introduced by the new KLL sketches and I will be moving back to Europe from the US in the next weeks :)

I asked a colleague of mine whether he has time to take care of a (pre)release soon

**Comment by rambrus** [comment]
@sscdotopen had a quick look at the `KLL sketches`, as I understand it's a new feature and can't introduce regression issues, since the the usage is optional and turned off by default. Is that correct? 
If so, would it make sense to introduce an @Experimental annotation for this feature and unblock the release?
Spark uses this approach in some cases (see [Experimental](https://spark.apache.org/docs/1.5.0/api/java/org/apache/spark/annotation/Experimental.html) for details)

**Comment by sscdotopen** [comment]
The KLL Sketches are used by default in the ColumnProfiler at the moment. We could modify the ColumnProfiler to not compute the KLL sketches by default, that would help unblock the release. Do you want to take a shot at this?

**Comment by rambrus** [comment]
All right, will take a look and get back to you.

**Comment by sscdotopen** [comment]
Thanks

**Comment by rambrus** [comment]
@esil-esil the above mentioned changes have been implemented in https://github.com/awslabs/deequ/pull/209

**Comment by rambrus** [comment]
@sscdotopen are there any other issues to be resolved before the release?

**Comment by esil-esil** [comment]
@rambrus , @sscdotopen :

I would really appreciate if fix of https://github.com/awslabs/deequ/issues/201 could also be included in the new release, though the filterable checks is what I am most urgently awaiting in a new release of the library.

In #201, I have uploaded a test case Databricks Notebook (scala) reproducing the error described in #201.

FYI @rambrus : I am software tester - not developer - so unfortunately I cannot fix the issue myself, but I will of course try to be as helpful as possible regarding how-2-reproduce steps (in the case of #201 in the format of a Notebook), and of course helping out re-testing/verifying after bug fixing. I am very grateful for all your help!

Given the current, very special global situation, Sebastian is probably very busy arriving back in Europe (ref. Sebastian's comment previously in this thread).

**Comment by rambrus** [comment]
@esil-esil @sscdotopen had a look at the above issue, I think I understand what's missing there. can't promise anything, but trying to help and prioritize this task. will get back to you once I have done some progress.

**Pull request merged**
