### PR TITLE
Add assertion param to convenience constraints

### PR DESCRIPTION
**Pull request by paulsukow**
Description of changes:
I want to use some of the convenience constraints, but with an assertion threshold.
I added a assertion param to the following check constraints:
- isPositive
- isNotNegative
- isLessThanOrEqualTo
- isLessThan
- isGreaterThanOrEqualTo
- isGreaterThan

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by paulsukow** [comment]
@sscdotopen Definitely. I will add some later this weekend

**Comment by paulsukow** [comment]
@sscdotopen Unit tests added

**Comment by sscdotopen** [comment]
Hi, the unit tests look good, but the build failed for some reasons, can you have a look at whats causing this?

**Comment by paulsukow** [comment]
@sscdotopen Fixed. I had a scala style error.

**Comment by sscdotopen** [comment]
Thank you!

**Pull request merged**
