### PR TITLE
sort suggested categories

### PR DESCRIPTION
**Pull request by aviatesk**
*Issue #, if available:*

*Description of changes:*

- sort suggested categorical values when generating constraint code (sort in lexical order)
- this may improve the readability of suggested constraints and help one refer to it as some form of the data schema

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by aviatesk** [comment]
@twollnik can we push this forward ?
This PR doesn't change any suggestion functionality itself, but just improve its referability, e.g.

> before
```scala
// suggested
isContainedIn("area_cd", Array("030", "060", "050", "090", "020", "080", "040", "010", "070"))
```

> after
```scala
// suggested
.isContainedIn("area_cd", Array("010", "020", "030", "040", "050", "060", "070", "080", "090")),
```

**Comment by twollnik** [comment]
We are explicitely ordering the values by popularity just a couple of lines earlier (`.sortBy { case (_, value) => value.absolute }`). @sscdotopen Do you know if there is a specific reason for this?

**Comment by aviatesk** [comment]
Ops, I just assumed they were unsorted.
Then maybe we should make it configurable at least ? Something like:
```scala
case class CategoricalRangeRule[A](
  sorter: ((String, DistributionValue)) => A = (a: (String, DistributionValue)) => a match { case (_, value) => value.absolute }
)(implicit ord: Ordering[A]) extends ConstraintRule[ColumnProfile] {
```

**Comment by aviatesk** [comment]
@twollnik any update ? How about adding `sorter` constructor argument ? An user can opt into to change that, but the default behaviour won't change.

**Comment by aviatesk** [comment]
okay, this should be good to go.
I decided to add a constructor option that allows each user to give their own category sorter. Since the default value is preserved same as the previous implementation, this PR shouldn't change any behavior by itself.

**Comment by twollnik** [comment]
Thanks for your patience on this!

**Pull request merged**
