### PR TITLE
Repositories to use AnalyzerId instead of Analyzer

### PR DESCRIPTION
**Pull request by timgent**
*Issue #, if available:*
https://github.com/awslabs/deequ/issues/232

*Description of changes:*
Updating repositories to store a map of analyzerId to metric, rather than the whole analyzer. Idea is that it makes extending repository more straight forward if you want to store metrics somewhere else, as you have some simpler thing to store, rather than storing Analyzer object itself. Should make it simpler to switch file system repository to store data in some more structured format rather than storing as serialized objects (which for example would be hard to do trend analysis with some external tool).

NOTE: This change will break backwards compatibility for people storing metrics with existing method.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by timgent** [comment]
Realise the code formatting check failed in CI - happy to fix that, though would be good to get feedback on the changes before I put more time into it

**Comment by sscdotopen** [comment]
Dear Tim,

Do you think there is a way to implement this without breaking backwards compatibility? Maybe via an optional parameter or so? It would be to dangerous to merge this otherwise.

**Comment by timgent** [comment]
@sscdotopen 2 ways I can think of to stop issues of backwards compatibility:

1) Could implement a fallback when reading data from the repository. If it fails to read a Map[AnalyzerId, Metric] it could fallback to reading Map[Analyzer, Metric], then just maps the values to get the AnalyzerId

2) Make the interface that a user could extend use AnalyzerId, but within the library convert from AnalyzerId to Analyzer... which feels a bit wrong.

Thoughts?

Also what do you think in terms of if this change is worth considering?

**Comment by sscdotopen** [comment]
Users can already store metrics in JSON form on disk, so I don't think we need to worry about serialized objects.

**Comment by timgent** [comment]
Ahh, looks like I got the wrong understanding of some bits of the code. Thanks for the clarification. I should be able to make this not break backwards compatibility in that case

**Comment by timgent** [comment]
@sscdotopen the change is now backwards compatibility - I added a test for that too just to make sure

**Comment by timgent** [comment]
@sscdotopen any more thoughts on this one?

**Comment by sscdotopen** [comment]
I am not sure about this PR, because we already have a serialisation mechanism in place

**Pull request closed without merging**
