### PR TITLE
Update readme install instructions, add settings.xml

### PR DESCRIPTION
**Pull request by twollnik**
*Issue #, if available:*

*Description of changes:*
- This PR updates the install instructions in the README to reflect that we now publish [one release per spark-scala version combination](https://repo1.maven.org/maven2/com/amazon/deequ/deequ/).
- The PR also adds the file `settings.xml` that is needed to publish maven releases. 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by aviatesk** [comment]
> The PR also adds the file settings.xml that is needed to publish maven releases.

Does this mean all the releases will appear in [maven repository](https://mvnrepository.com/artifact/com.amazon.deequ/deequ) with this change ?
If so looks good to me.

**Comment by twollnik** [comment]
Thanks for the comment. The releases are already due to appear in the maven repository, it can just take some time for the change to be visible. If you check back throughout the day you should see more and more releases `1.1.0_[...]` appear.

Let's wait till EOD, I will merge the changes then.

**Comment by twollnik** [comment]
Update: Still not all artifacts are available on [maven](https://mvnrepository.com/artifact/com.amazon.deequ/deequ). Let's see what happens until monday. If they are still not uploaded by then I will inverstigate further.

**Comment by aviatesk** [comment]
sounds good, thanks for taking care of the release process !

**Review by r-aviatesk — APPROVED** [review]
It seems that all the artifacts are appearing on the maven repository.

**Pull request merged**
