### PR TITLE
Add Row Level Semantic Checks and Isolate Failed Checks with RowValidator Object 

### PR DESCRIPTION
**Pull request by noahpaige13**
…g rows

*Issue #, if available: 283

*Description of changes: Created a RowValidator feature that can handle semantic checks (i.e. isContainedIn, containsEmail, isInRage, etc.) and identifies which checks failed so that bad records can be put into a reject queue for some data steward to examine.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by sohumsachathamakul** [comment]
@noah-paige - great work! What's remaining to take this over the finishing line?

**Comment by sohum2002** [comment]
@noahpaige13  - great work! What's remaining to take this over the finishing line?

**Comment by sscdotopen** [comment]
This looks very good, but could you integrate your changes in the already existing code: https://github.com/awslabs/deequ/blob/master/src/main/scala/com/amazon/deequ/schema/RowLevelSchemaValidator.scala

**Comment by noahpaige13** [comment]
Integrated the RowValidator functionality into the existing RowLevelSchemaValidator so that the tool can handle both schema checks and other semantical ones. 

Also added a statistics dataframe as output when calling the validate method with the percentage of rows that failed each check and the percentage of total invalid rows from the original dataframe.

**Comment by sscdotopen** [comment]
Somehow this PR touches 191 files, I guess there is something wrong here.

**Pull request closed without merging**
